#include <iostream>
#include <string>

/*
 Advent of Code 2015 – Day 10

    Problem:
        Determine the length of a sequence generated by facross 40 or 50 iterations. 

    Approach:
        Defines lambda to perform look and say game
        `std::move` the output into the original input string to avoid unncessary allocations
        Invokes lambda for the specified number of iterations
    
    Complexity:
        O(n * 2^k) -- where n is the input length and k is the number of iterations
        O(2^k) -- where k is the number o iterations
*/

int main(int argc, char* argv[]) {
  if (argc < 2) {
    std::cerr << "please provide an input as an agrument\n";
    return -1;
  }

  auto look_and_say = [](auto& input) {
    std::string output{};
    output.reserve(input.size() * 2);

    size_t i{1};
    size_t count{1};
    while (i < input.size()) {
      if (input[i - 1] == input[i]) {
        ++count;
      } else {
        output += std::to_string(count) + input[i - 1];
        count = 1;
      }
      ++i;
    }
    output += std::to_string(count) + input[input.size() - 1];
    
    input = std::move(output);
  };

  size_t iterations{50};
  std::string result{argv[1]};

  while (iterations > 0) {
    look_and_say(result);
    --iterations;
  }

  std::cout << result.size() << '\n';

  return 0;
}